// nuxt/components/Footer.vue
<script lang="ts">
import { Vue, Component, Prop } from 'vue-property-decorator';
import BrandIcon from './BrandIcon';

interface FooterIcon {
    company: string;
    url: string;
    size: string;
}

@Component({
  components: {
    BrandIcon,
  },
})
export default class Footer extends Vue {
  icons: FooterIcon[] = [
    {
      company: 'linkedin-in',
      url: 'https://www.linkedin.com/in/seanwatters',
      size: 'md',
    },
    {
      company: 'medium-m',
      url: 'https://medium.com/@sean_watters',
      size: 'md',
    },
    {
      company: 'twitter',
      url: 'https://twitter.com/sean_watters',
      size: 'md',
    },
    {
      company: 'github',
      url: 'https://github.com/seanwatters',
      size: 'md',
    },
    {
      company: 'gitlab',
      url: 'https://gitlab.com/sean_watters',
      size: 'md',
    },
  ];

  @Prop() readonly theme!: string;
}
</script>

<template>
  <footer :style="`background-color: ${theme === 'dark' ? 'black' : 'white'}`">
    <nav class="external-icons">
      <a v-for="{ company, url, size } in icons" :key="company" :href="url" :aria-label="'Link to ' + company">
        <BrandIcon :company="company" :color="theme === 'dark' ? 'white' : 'black'" :size="size" />
      </a>
    </nav>
    <div class="tm" :style="`color: ${theme === 'dark' ? 'white' : 'black'}`">
      © 2020 sean watters
    </div>
  </footer>
</template>

<style lang="css" scoped>
    footer {
        width: 100vw;
        display: flex;
        flex-direction: column;
        align-items: center;
        padding-top: 100px;
    }
    .external-icons {
        width: 67.5vw;
        display: flex;
        flex-direction: row;
        justify-content: space-between;
    }
    .tm {
        font-size: 0.5rem;
        padding: 10px;
        text-transform: capitalize;
    }
    @media (min-width: 576px) {
        .external-icons {
            width: 45vw;
        }
    }

    @media (min-width: 768px) {
        .external-icons {
            width: 37.5vw;
        }
    }

    @media (min-width: 992px) {
        .external-icons {
            width: 25vw;
        }
    }

    @media (min-width: 1200px) {
        .external-icons {
            width: 18vw;
        }
    }
</style>

// components/Footer.tsx
import React from 'react';
import BrandIcon, { Icon } from './BrandIcon';

interface FooterIcon extends Icon {
  url: string
}

const icons: FooterIcon[] = [
  {
    company: 'linkedin-in',
    url: 'https://www.linkedin.com/in/seanwatters',
    size: 32.5,
  },
  {
    company: 'medium-m',
    url: 'https://medium.com/@sean_watters',
    size: 32.5,
  },
  {
    company: 'twitter',
    url: 'https://twitter.com/sean_watters',
    size: 32.5,
  },
  {
    company: 'github',
    url: 'https://github.com/seanwatters',
    size: 32.5,
  },
  {
    company: 'gitlab',
    url: 'https://gitlab.com/sean_watters',
    size: 32.5,
  },
];

const Footer = ({ theme }: {theme: string}) => (
  <>
    <footer>
      <nav className="external-icons">
        {icons.map(({ company, url, size }: FooterIcon) => (
          <a key={Math.random() + company} href={url} aria-label={`Link to  ${company}`}>
            <BrandIcon company={company} color={theme === 'dark' ? 'white' : 'black'} size={size} />
          </a>
        ))}
      </nav>
      <div className="tm">© 2020 sean watters</div>
    </footer>
    <style jsx>{`
        footer {
            width: 100vw;
            background-color: ${theme === 'dark' ? 'black' : 'white'};
            display: flex;
            flex-direction: column;
            align-items: center;
            padding-top: 100px;
        }
        .external-icons {
            width: 67.5vw;
            display: flex;
            flex-direction: row;
            justify-content: space-between;
        }
        .tm {
            color: ${theme === 'dark' ? 'white' : 'black'};
            font-size: 0.5rem;
            padding: 10px;
            text-transform: capitalize;
        }
        @media (min-width: 576px) { 
            .external-icons {
                width: 45vw;
            }
        }

        @media (min-width: 768px) { 
            .external-icons {
                width: 37.5vw;
            }
        }

        @media (min-width: 992px) {
            .external-icons {
                width: 25vw;
            }
        }

        @media (min-width: 1200px) { 
            .external-icons {
                width: 18vw;
            }
        }
    `}
    </style>
  </>
);

export default Footer;
