// vue/pages/index.vue
<script lang="ts">
import { Vue, Component } from 'vue-property-decorator';
import Layout from '@/components/Layout';
import SectionOne from '@/components/HomePage/SectionOne';
import SectionTwo from '@/components/HomePage/SectionTwo';
import SectionThree from '@/components/HomePage/SectionThree';

@Component({
  components: {
    Layout,
    SectionOne,
    SectionTwo,
    SectionThree,
  },
})
export default class Home extends Vue {
    sectionOneVisible: boolean = false;
    sectionTwoVisible: boolean = false;
    sectionThreeVisible: boolean = false;
    sectionFourVisible: boolean = false;

    mounted () {
      this.sectionOneVisible = true;

      setTimeout(() => {
        this.sectionTwoVisible = true;
      }, 1000);
      setTimeout(() => {
        this.sectionThreeVisible = true;
      }, 2000);
    }
}
</script>

<template>
  <div class="container">
    <Layout theme="dark" location="Home">
      <SectionOne :is-visible="sectionOneVisible" />
      <SectionTwo :is-visible="sectionTwoVisible" />
      <SectionThree :is-visible="sectionThreeVisible" />
    </Layout>
  </div>
</template>

<style lang="css">
</style>

// nextjs/pages/index.tsx
import React, { useState, useEffect, useRef } from 'react';

import useScroll from 'hooks/useScroll';
import Layout from 'components/Layout';

import SectionOne from 'components/Homepage/SectionOne';
import SectionTwo from 'components/Homepage/SectionTwo';
import SectionThree from 'components/Homepage/SectionThree';
// import SectionFour from 'components/Homepage/SectionFour';

const Home = () => {
  const { scrollY } = useScroll();

  const sectionOne = useRef<HTMLElement>(null);
  const sectionTwo = useRef<HTMLElement>(null);
  const sectionThree = useRef<HTMLElement>(null);
  const sectionFour = useRef<HTMLElement>(null);

  const [sectionOneVisible, setSectionOneVisible] = useState(false);
  const [sectionTwoVisible, setSectionTwoVisible] = useState(false);
  const [sectionThreeVisible, setSectionThreeVisible] = useState(false);
  const [sectionFourVisible, setSectionFourVisible] = useState(false);

  useEffect(() => {
    let breakpoint = 500;
    if (typeof window !== 'undefined') {
      breakpoint = window.innerHeight / 2;
    }
    if (!sectionOneVisible
          && sectionOne.current
          && sectionOne.current.getBoundingClientRect().top < breakpoint
    ) { setSectionOneVisible(true); }

    if (!sectionTwoVisible
          && sectionTwo.current
          && sectionTwo.current.getBoundingClientRect().top < breakpoint
    ) { setSectionTwoVisible(true); }

    if (!sectionThreeVisible
        && sectionThree.current
        && sectionThree.current.getBoundingClientRect().top < breakpoint
    ) { setSectionThreeVisible(true); }

    if (!sectionFourVisible
          && sectionFour.current
          && sectionFour.current.getBoundingClientRect().top < breakpoint
    ) { setSectionFourVisible(true); }

  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [scrollY]);

  return (
    <>
      <Layout theme="dark" title="Sean Watters — Software Engineer">
        <SectionOne isVisible={sectionOneVisible} refInjection={sectionOne} />
        <SectionTwo isVisible={sectionTwoVisible} refInjection={sectionTwo} />
        <SectionThree isVisible={sectionThreeVisible} refInjection={sectionThree} />
        {/* <SectionFour isVisible={sectionFourVisible} refInjection={sectionFour} /> */}
      </Layout>
    </>
  );
};

export default Home;
