// components/Layout.tsx
import React from 'react';
import Head from 'next/head';

import Header from './Header';
import Footer from './Footer';

interface Props {
    children: any[] | any;
    title: string;
    location?: string;
    theme?: string;
}

const Layout = ({
  children,
  title,
  location,
  theme = 'light',
}: Props) => (
  <>
    <div id="page-container">
      <Head>
        <title>{title}</title>
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="description"
          content="Information about Sean Watters."
        />

        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-167813886-1" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){dataLayer.push(arguments);}
                  gtag('js', new Date());
                  gtag('config', 'UA-167813886-1');
              `,
          }}
        />

      </Head>
      <Header
        theme={theme}
        location={location}
      />
      <main>
        {children}
      </main>
      <Footer theme={theme} />
    </div>

    <style jsx>{`
      main {
        width: 100vw;
        overflow: hidden;
        padding-top: 35px;
      } 
  `}
    </style>
  </>
);

export default Layout;

// sapper/src/components/Layout.svelte
<script lang="ts">
  import Header from './Header.svelte';
  import Footer from './Footer.svelte';

  export let location: string | null = null;
  export let theme: string;
  export let title: string;
</script>

<svelte:head>
  <script
    src="https://kit.fontawesome.com/89c2981c8d.js"
    crossorigin="anonymous"
    async>
  </script>
  <!--<script
    async
    src="https://www.googletagmanager.com/gtag/js?id=UA-167813886-1" ✂prettier:content✂="CiAg" ✂prettier:content✂="e30=">{}</script><script>
    window.dataLayer = window.dataLayer || [];
    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-167813886-1');
  </script>-->
</svelte:head>

<Header location="{location}" />

<main>
  <slot />
</main>

<Footer theme="{theme}" />

<style>
  main {
    width: 100vw;
    overflow: hidden;
    padding-top: 35px;
  }
</style>
