// nextjs/pages/index.tsx
import React, { useState, useEffect, useRef } from 'react';

import useScroll from 'hooks/useScroll';
import Layout from 'components/Layout';

import SectionOne from 'components/Homepage/SectionOne';
import SectionTwo from 'components/Homepage/SectionTwo';
import SectionThree from 'components/Homepage/SectionThree';
// import SectionFour from 'components/Homepage/SectionFour';

const Home = () => {
  const { scrollY } = useScroll();

  const sectionOne = useRef<HTMLElement>(null);
  const sectionTwo = useRef<HTMLElement>(null);
  const sectionThree = useRef<HTMLElement>(null);
  const sectionFour = useRef<HTMLElement>(null);

  const [sectionOneVisible, setSectionOneVisible] = useState(false);
  const [sectionTwoVisible, setSectionTwoVisible] = useState(false);
  const [sectionThreeVisible, setSectionThreeVisible] = useState(false);
  const [sectionFourVisible, setSectionFourVisible] = useState(false);

  useEffect(() => {
    let breakpoint = 500;
    if (typeof window !== 'undefined') {
      breakpoint = window.innerHeight / 2;
    }
    if (!sectionOneVisible
          && sectionOne.current
          && sectionOne.current.getBoundingClientRect().top < breakpoint
    ) { setSectionOneVisible(true); }

    if (!sectionTwoVisible
          && sectionTwo.current
          && sectionTwo.current.getBoundingClientRect().top < breakpoint
    ) { setSectionTwoVisible(true); }

    if (!sectionThreeVisible
        && sectionThree.current
        && sectionThree.current.getBoundingClientRect().top < breakpoint
    ) { setSectionThreeVisible(true); }

    if (!sectionFourVisible
          && sectionFour.current
          && sectionFour.current.getBoundingClientRect().top < breakpoint
    ) { setSectionFourVisible(true); }

  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [scrollY]);

  return (
    <>
      <Layout theme="dark" title="Sean Watters — Software Engineer">
        <SectionOne isVisible={sectionOneVisible} refInjection={sectionOne} />
        <SectionTwo isVisible={sectionTwoVisible} refInjection={sectionTwo} />
        <SectionThree isVisible={sectionThreeVisible} refInjection={sectionThree} />
        {/* <SectionFour isVisible={sectionFourVisible} refInjection={sectionFour} /> */}
      </Layout>
    </>
  );
};

export default Home;

// nuxt/pages/index.vue
<script lang="ts">
import { Vue, Component } from 'vue-property-decorator';
import Layout from '@/components/Layout';
import SectionOne from '@/components/HomePage/SectionOne';
import SectionTwo from '@/components/HomePage/SectionTwo';
import SectionThree from '@/components/HomePage/SectionThree';

@Component({
  components: {
    Layout,
    SectionOne,
    SectionTwo,
    SectionThree,
  },
  head: {
    title: 'Sean Watters — Software Engineer',
  },
})
export default class Home extends Vue {
    sectionOneVisible: boolean = false;
    sectionTwoVisible: boolean = false;
    sectionThreeVisible: boolean = false;
    sectionFourVisible: boolean = false;

    // Can't use actual $ref bc it doesn't like `getBoundingClientRect`
    sectionTwoRef: HTMLElement | null = null
    sectionThreeRef: HTMLElement | null = null
    sectionFourRef: HTMLElement | null = null

    handleScroll () {
      if (this.sectionTwoRef && this.sectionTwoRef.getBoundingClientRect().top < 500) { this.sectionTwoVisible = true; };
      if (this.sectionThreeRef && this.sectionThreeRef.getBoundingClientRect().top < 500) { this.sectionThreeVisible = true; };
      if (this.sectionFourRef && this.sectionFourRef.getBoundingClientRect().top < 500) { this.sectionFourVisible = true; };
    }

    mounted () {
      this.sectionOneVisible = true;
      this.sectionTwoRef = document.getElementById('home-page-section-2');
      this.sectionThreeRef = document.getElementById('home-page-section-3');
      this.sectionFourRef = document.getElementById('home-page-section-4');

      window.addEventListener('scroll', this.handleScroll);
    }
}
</script>

<template>
  <div class="container">
    <Layout theme="dark">
      <SectionOne id="home-page-section-1" :is-visible="sectionOneVisible" />
      <SectionTwo id="home-page-section-2" :is-visible="sectionTwoVisible" />
      <SectionThree id="home-page-section-3" :is-visible="sectionThreeVisible" />
    </Layout>
  </div>
</template>
